// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'html', 
      value: 'Introduction',
      className: 'menu__category', 
    },
    'introduction/orion',
    'introduction/design_principles',


    {
      type: 'html', 
      value: '&nbsp;',
      className: 'menu__spacer',
    },

    {
      type: 'html', 
      value: 'Protocol Design',
      className: 'menu__category',
    },
    'protocol_design/overview',
    'protocol_design/tokenomics',

    {
      type: 'html', 
      value: '&nbsp;',
      className: 'menu__spacer',
    },

    {
      type: 'html', 
      value: 'Key Features',
      className: 'menu__category',
    },
    'key_features/financial_machine_learning',
    'key_features/fhEVM',
    'key_features/vaults',
  ],
};
export default sidebars;
