// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'html', // Non-clickable title
      value: 'Introduction',
      className: 'menu__category menu__spacer', // Adds padding
    },
    'intro', // Clickable doc under Introduction

    {
      type: 'html', // Add spacing before the new title
      value: '&nbsp;', // Empty space
      className: 'menu__spacer',
    },

    {
      type: 'html', // New non-clickable title
      value: 'Advanced Topics',
      className: 'menu__category menu__spacer',
    },
    {
      type: 'category',
      label: 'Docs Basics',
      collapsed: true,
      items: [
        'docs-basics/congratulations',
        'docs-basics/create-a-blog-post',
        'docs-basics/create-a-document',
        'docs-basics/create-a-page',
        'docs-basics/deploy-your-site',
        'docs-basics/markdown-features',
      ],
    },

    {
      type: 'category',
      label: 'Docs Extras',
      collapsed: true,
      items: [
        'docs-extras/manage-docs-versions',
        'docs-extras/translate-your-site',
      ],
    },
  ],
};
export default sidebars;
